mapbox/mapbox-events-android

- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
- Fixes service not starting/stopping properly
- Because we're using a bound service we need to call explicitly to `startService` and `bindService` when starting location and `unbindService` (if bounded) and `stopService` when stopping location
👀 @electrostat
> Fix service not starting/stopping properly

- liblocation/src/main/java/com/mapbox/services/android/core/location/LocationEngine.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryService.java
Adjust placement of @LocationEnginePriority.PowerMode annotations to match rest of codebase.,
> Adjust PowerMode Annotations

- .circleci/config.yml
- .gitignore
- gradle/dependencies.gradle
- libcore/src/main/java/com/mapbox/services/android/core/connectivity/ConnectivityReceiver.java
- libcore/src/main/res/values/strings.xml
- liblocation/src/main/res/values/strings.xml
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/MapEventFactory.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryClient.java
- Fixes CI image (`mbgl/83e63ed4e7:android-ndk-r16b`)
- Bumps `buildToolsVersion` to `25.0.3`
- Fixes `.gitignore`
- Fixes Lint issues in `libcore`, `liblocation` and `libtelemetry`
> Fix CI config

- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/Event.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/MapEventFactory.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/NavigationEventFactory.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/NavigationFasterRouteEvent.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryClient.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryService.java
- libtelemetry/src/test/java/com/mapbox/services/android/telemetry/AppUserTurnstileTest.java
- libtelemetry/src/test/java/com/mapbox/services/android/telemetry/LocationEventTest.java
- libtelemetry/src/test/java/com/mapbox/services/android/telemetry/MapEventFactoryTest.java
- libtelemetry/src/test/java/com/mapbox/services/android/telemetry/NavigationEventFactoryTest.java
- libtelemetry/src/test/java/com/mapbox/services/android/telemetry/TelemetryClientNavigationEventsTest.java
- Adds family type checking to `MapEventFactory` and `NavigationEventFactory`
> Add family type checking to map and navigation events factories

- libcore/src/main/java/com/mapbox/services/android/core/connectivity/ConnectivityReceiver.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryService.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryUtils.java
- libtelemetry/src/test/java/com/mapbox/services/android/telemetry/MapboxTelemetryTest.java
- General clean up:
- Remove unnecessary code https://github.com/mapbox/mapbox-events-android/blob/667615a72364e118022133583ff5cc2bc1b44e6e/libtelemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryService.java#L185-L223 brought back in https://github.com/mapbox/mapbox-events-android/pull/12
- Avoid security exceptions around `MapboxTelemetry#isNetworkConnected()`
- Formatting + code organization
👀 @zugaldia @electrostat
> General clean up

- liblocation/src/main/java/com/mapbox/services/android/core/permissions/PermissionsListener.java
- Fixes modifier of `PermissionsListener` 👉 `public`
> Fix modifier of permissions listener

- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryService.java
- Fixes default `locationPriority` 👉 `LocationEnginePriority.NO_POWER`
👀 @zugaldia @electrostat
> Fix default location engine priority

- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/LocationMapper.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/LocationReceiver.java
- Fixes code organization of `LocationMapper` and `LocationReceiver`
👀 @zugaldia @electrostat
> Fix code organization of location mapper and location receiver

- libcore/src/main/AndroidManifest.xml
- libtelemetry/src/main/AndroidManifest.xml
- Follow up from external PR in #36 to allow CI to execute
Fixes #34 
cc @jush
> Reorganize location-related manifest entries

- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryService.java
Use existing methods to replace current code to remove, reset priority, add and reactivate location engine.
> Re-register Location engine listener properly when updating location priority

- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/PermissionCheckRunnable.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
- Adapts code to expose only `enable()` and `disable()` APIs
> Adapt code to expose only enable and disable APIs

- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClient.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
- Adds late token initialization support
> Add late token initialization support

- libtelemetry/src/main/java/com/mapbox/android/telemetry/AppUserTurnstile.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapEventFactory.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/AppUserTurnstileTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MapEventFactoryTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MockWebServerTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientAppUserTurnstileEventTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientMapEventsTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientNavigationEventsTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientTest.java
Create a solution for storing and retrieving 'vendorId' string that is used within appUserTurnstile and MapLoad Events
> Store MapboxVendorId

- libtelemetry/src/main/java/com/mapbox/android/telemetry/StagingCertificatePins.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/CertificatePinnerFactoryTest.java
- Fixes staging certificate pins endpoint to `api-events-staging.tilestream.net`
👀 @electrostat @boundsj @zugaldia
> Fix staging certificate pins endpoint

- libtelemetry/src/main/java/com/mapbox/android/telemetry/AlarmReceiver.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationReceiver.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/Logger.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/SchedulerCallback.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/SchedulerFlusher.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/SchedulerFlusherFactory.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/SchedulerFlusherJobService.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/AppUserTurnstileTest.java
> Fix a bunch of TODOs

- liblocation/src/main/java/com/mapbox/android/core/location/AndroidLocationEngine.java
- liblocation/src/main/java/com/mapbox/android/core/location/GoogleLocationEngine.java
- liblocation/src/main/java/com/mapbox/android/core/location/LostLocationEngine.java
- liblocation/src/main/java/com/mapbox/android/core/location/UpdateAndroidProvider.java
- liblocation/src/main/java/com/mapbox/android/core/location/UpdateGoogleRequestPriority.java
- liblocation/src/main/java/com/mapbox/android/core/location/UpdateLostRequestPriority.java
- liblocation/src/main/java/com/mapbox/services/android/core/location/UpdateAndroidProvider.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryListener.java
Move 4 files into correct package. Issue from rebase.
> Change Packages

- libtelemetry/src/main/java/com/mapbox/android/telemetry/AppUserTurnstile.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryEnabler.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/AppUserTurnstileTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MockWebServerTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientAppUserTurnstileEventTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientNavigationEventsTest.java
- Deals with telemetry state properly when calling to `enable`/`disable` APIs
> Deal with telemetry state properly

- gradle/dependencies.gradle
- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
- libtelemetry/src/main/AndroidManifest.xml
- libtelemetry/src/test/java/com/mapbox/android/telemetry/NavigationEventFactoryTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/SerializerTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientNavigationEventsTest.java
Some tail work needed after removing Lost completely (👀 #81)
- Removes Lost dependency from `dependencies.gradle` file
- Fixes Javadoc referencing to Lost
- Removes `tools:overrideLibrary="com.mapzen.lost"` from the `libtelemetry` `AndroidManifest`
- Fixes tests referencing to Lost
> Remove Lost tail work

- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryEnabler.java
Meta-data tag should be optional
> Meta-Data Tag Optional

- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
Sending wrong userAgent when collecting events. Changes need to be made to when FullUserAgent is created and for formatting the user agent properly.
> Incorrect UserAgent

- CONTRIBUTING.md
- README.md
This pr adds much more information to this repo's README file so that the README is more in line with our other repos' README files. If there should be more information about adding the telem library independently, let me know.
> README upgrade

- libtelemetry/src/main/java/com/mapbox/android/telemetry/FeedbackEventData.java
- Generates `userId` (`vendorId`) from `FeedbackEventData` internally
:eyes: @zugaldia @electrostat
> Generate user id from feedback event data internally

- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
Change formatting for `AndroidLocationEngine` within javadoc
> AndroidLocationEngine javadoc format change

- libtelemetry/src/main/java/com/mapbox/android/telemetry/ChinaCertificatePins.java
Generate new hashes for the new certificates used in china.
> Add new China Certificate Hashes

- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
Close response body when returned from okhttp request
> Close Okhttp Response

- libtelemetry/gradle.properties
Reset Snapshot count down to 3.2.0
> Reset Snapshot to 3.2.0

- libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationEvent.java
- Makes `LocationEvent` constructor package-private
> Make location event constructor package private

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/mapbox/android/events/testapp/MainActivity.java
- libtelemetry/src/main/AndroidManifest.xml
- libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationJobService.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
Create an enhanced location job system. Use previous locations to know if to turn on location collection (similar to geofence system). Keep location collection on longer, but balance against battery usage. Get better location data.
> Enhanced Location Jobs

- gradle/dependencies.gradle
- downgrade ArchLifecycleVersion to 1.1.0
Fixes https://github.com/mapbox/mapbox-gl-native/issues/12383#issuecomment-405961493
> Downgrade ArchLifecycleVersion

- README.md
Part of https://github.com/mapbox/mapbox-events-android/issues/194
> Core 0.2.1 version README update

- libtelemetry/src/main/java/com/mapbox/android/telemetry/AttachmentListener.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClient.java
- change name of variable from `fieldIds` to `fileIds`
> Change fieldIds to fileIds

- .circleci/config.yml
- app/build.gradle
- gradle/dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
- libcore/build.gradle
- libcore/javadoc.gradle
- liblocation/build.gradle
- libtelemetry/build.gradle
- libtelemetry/javadoc.gradle
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
Fixes https://github.com/mapbox/mapbox-events-android/issues/219
> Update dependencies and cleanup gradle scripts

- app/build.gradle
- liblocation/src/main/java/com/mapbox/android/core/location/LocationUpdatesBroadcastReceiverProxy.java
- libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/LocationReceiverInstrumentationTest.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationReceiver.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/LocationReceiverTest.java
This PR addresses https://github.com/mapbox/mapbox-events-android/issues/159 and https://github.com/mapbox/mapbox-events-android/issues/163
> Telemetry SDK background location updates + batch locations

- CHANGELOG.md
- update changelog to reflect 3.4.0 release changes
> Update changelog to match 3.4.0 release

- libtelemetry/src/main/java/com/mapbox/android/telemetry/Event.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/VisionEventFactory.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/VisionObjectDetectionEvent.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/SchemaTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/VisionEventFactoryTest.java
Note: Please refrain from using `VisionEventFactory` it is rather redundant and will be deprecated. 
/cc @l-r
> Add support for Vision object detection event (v2)

- libtelemetry/src/main/java/com/mapbox/android/telemetry/VisionObjectDetectionEvent.java
> Typo fixes.

- build.gradle
- libcore/build.gradle
- liblocation/build.gradle
- liblocation/src/androidTest/java/com/mapbox/android/core/location/LocationEngineInstrumentedTest.java
- liblocation/src/main/java/com/mapbox/android/core/location/AbstractLocationEngineImpl.java
- liblocation/src/main/java/com/mapbox/android/core/location/AndroidLocationEngineImpl.java
- liblocation/src/main/java/com/mapbox/android/core/location/ForegroundLocationEngine.java
- liblocation/src/main/java/com/mapbox/android/core/location/GoogleLocationEngineImpl.java
- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineImpl.java
- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineProvider.java
- liblocation/src/main/java/com/mapbox/android/core/location/MapboxFusedLocationEngineImpl.java
- liblocation/src/main/java/com/mapbox/android/core/location/Utils.java
- liblocation/src/test/java/com/mapbox/android/core/location/LocationEngineTest.java
First attempt to improve user experience with MapboxFusedLocationEngine on devices where Google Play Services are not available. 
/cc @mapbox/android
> Mapbox Fused Location Engine

- CHANGELOG.md
- libtelemetry/gradle.properties
Update changelog to reflect 3.5.0 telemetry release.
> 3.5.0 Changelog

- liblocation/src/main/java/com/mapbox/android/core/location/GoogleLocationEngineImpl.java
- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineResult.java
> Handle potential 'null' last location returned by fused client

- CHANGELOG.md
Update changelog to reflect 3.5.1 telemetry release.
> 3.5.1 Changelog

- .circleci/config.yml
- CHANGELOG.md
- libcore/gradle.properties
- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineProvider.java
- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineRequest.java
- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineResult.java
- libtelemetry/gradle.properties
Releasing Telemetry 4.0.0 and Core 1.0.0
Addresses https://github.com/mapbox/mapbox-events-android/issues/259
cc: @andrlee
> 4.0.0 Telemetry + 1.0.0 Core Release

- app/build.gradle
- gradle/jacoco.gradle
- libcore/build.gradle
- liblocation/build.gradle
- libtelemetry/build.gradle
Integrate jacoco with events repo. Note this will only work/testes with AGP 3.2 and Gradle 4.6.
> Integrate jacoco plugin with events repo

- ci.template
Create new Cloudformation CI user template for getting access to mapbox loading dock from CircleCI directly.
> Add new CI user template

- CHANGELOG.md
Update changelog to reflect 3.5.4 telemetry release.
> 3.5.4 Changelog

- CHANGELOG.md
Update changelog to reflect 3.5.2 telemetry release.
> 3.5.2 Changelog

- .circleci/config.yml
- scripts/capture_binary_size_for_aws.sh
- scripts/check_binary_size.sh
Publish binary size on master and release branch only.
> Publish metrics to AWS on master and release only

- CHANGELOG.md
Update Changleog for 3.5.5 release
> Update Changelog for 3.5.5

- CHANGELOG.md
> Update 3.5.6 Changelog

- .circleci/config.yml
- CHANGELOG.md
- libcore/gradle.properties
- libtelemetry/gradle.properties
Releasing Telemetry 4.1.0 and Core 1.1.0
Addresses https://github.com/mapbox/mapbox-events-android/issues/300
cc: @andrlee
> 4.1.0 Telemetry + 1.1.0 Core Release

- CHANGELOG.md
> 3.5.7 Changelog Update 

- CHANGELOG.md
> Update changelog  for 3.5.8 Release

- Makefile
Fixing telem lite release command
> Fix make command

- libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/ConfigurationClientInstrumentationTest.java
Fix one wrong test case, add two test cases to verify getting the correct endpoint
> Add more test cases for ConfigurationClient

- libtelemetry/build.gradle
Including libcore into lite version to fix compile time errors in china plugin
> Include libcore into lite version

- libcore/src/test/java/com/mapbox/android/core/DummyTest.java
- libcore/src/test/java/com/mapbox/android/core/crashreporter/MapboxUncaughtExceptionHanlderTest.java
- libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/AlarmMangerInstrumentationTest.java
Restore accidentally deleted unit test.
> Restore accidentally deleted test

- .circleci/config.yml
> Update tag regex

- .circleci/config.yml
- Makefile
Fix maven release step on CI and update javadoc release command.
> Fix maven release step

- CHANGELOG.md
- libcore/gradle.properties
Update release notes and bump snapshot version: https://github.com/mapbox/mapbox-events-android/issues/391
> Core 1.3.0 release

- CHANGELOG.md
Update release notes: https://github.com/mapbox/mapbox-events-android/issues/393
> Telemetry 4.4.1 release

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
Add issue template to simplify/streamline bug reporting process
> Add issue templates

- .github/ISSUE_TEMPLATE/release.md
Add release template to events repo
> Add release template

- CHANGELOG.md
- libtelemetry/gradle.properties
Update changelog and bump snapshot version for the upcoming release: https://github.com/mapbox/mapbox-events-android/issues/408
> Update changelog & bump snapshot version

- README.md
This repo's README needed a fix to the SNAPSHOT section
> Readme SNAPSHOT fix

- CHANGELOG.md
Update change log for telemetry patch release: https://github.com/mapbox/mapbox-events-android/issues/414
> Update change log for release 4.5.1

- CHANGELOG.md
- libtelemetry/gradle.properties
Update change log for telemetry release: #421
> Update changelog for release 4.6.0

- liblocation/src/main/java/com/mapbox/android/core/location/AndroidLocationEngineImpl.java
- liblocation/src/main/java/com/mapbox/android/core/location/GoogleLocationEngineImpl.java
- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineRequest.java
- liblocation/src/main/java/com/mapbox/android/core/location/MapboxFusedLocationEngineImpl.java
boyscouting - saw a typo and fixed all occurrences of it
> fix: typo displacemnt => displacement

- .circleci/config.yml
- cloud_test.sh
- libcore/src/androidTest/java/com/mapbox/android/core/crashreporter/CrashReportBuilderInstrumentedTest.java
- libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/AlarmMangerInstrumentationTest.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/AlarmSchedulerFlusher.java
This reverts commit 99441e2fcc7cb91643f65b6c6ceb1357019972bd.
> Revert "Add test device for CI in release process (#417)"

- libcore/gradle.properties
- libtelemetry/gradle.properties
Core - 1.4.2-SNAPSHOT
Telemetry - 4.7.2-SNAPSHOT
> Update Next Release Versions

- CHANGELOG.md
- libcore/gradle.properties
- libcore/src/main/assets/sdk_versions/com.mapbox.android.core
- libtelemetry/gradle.properties
- libtelemetry/src/main/assets/sdk_versions/com.mapbox.android.telemetry
Update Snapshot versions fro future releases .
Update changelog.md .
> Pre Release 4.7.4/1.4.2:

- CHANGELOG.md
- libcore/gradle.properties
- libcore/src/main/assets/sdk_versions/com.mapbox.android.core
- libtelemetry/gradle.properties
- libtelemetry/src/main/assets/sdk_versions/com.mapbox.android.telemetry
Pre release step:
Update Snapshot versions to Core 1.4.4-SNAPSHOT and Telemetry 4.7.6-SNAPSHOT.
Update CHANGELOG.MD
> Update SNAPSHOT versions and CHANGELOG.MD

- libcore/proguard-consumer.pro
Resolves #487 
Co-authored-by: harvsu <harsha.sura@mapbox.com>
> Add Proguard rules for gms classes

- gradle/dependencies.gradle
- gradle/jacoco.gradle
- gradle/wrapper/gradle-wrapper.properties
- Update gradle version to 6.5 and android gradle plugin version to 4.0.0
- Address breaking changes in jacoco.gradle
- Update android-sdk-versions-plugn to version 1.1.0
> Update gradle version

- app/src/main/AndroidManifest.xml
- liblocation/src/main/java/com/mapbox/android/core/permissions/PermissionsManager.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationEngineControllerImpl.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/SchemaTest.java
Add background location permission support in the PermissionsManager. Also, request location permissions based on the declarations in the manifest, instead of requesting fine location permission by default.
> [core] Add background location permission

- CHANGELOG.md
- libcore/gradle.properties
- libtelemetry/gradle.properties
Telemetry 6.2.0 and Core 3.1.0
> [changelog] Update changelog for Telemetry  and Core

- CHANGELOG.md
- libtelemetry/gradle.properties
> [changelog] Update changelog for Telemetry

- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineRequest.java
- liblocation/src/test/java/com/mapbox/android/core/location/LocationEngineRequestTest.java
Resolves https://github.com/mapbox/mapbox-events-android/issues/506
> Add equals and hash to LocationEngineRequest

- CHANGELOG.md
- libcore/gradle.properties
- libtelemetry/gradle.properties
Telemetry 7.0.0 and Core 4.0.0
> [changelog] Update changelog for Telemetry and Core

- .circleci/config.yml
Those jobs were disabled before due to a lack of credentials.
> [ci] Revert disabled CI jobs back.

- CHANGELOG.md
Update changelog for a new release of libcore v5.0.0 and libtelemetry v8.0.0.
> [changelog] Update changelog for a new release

- CHANGELOG.md
- libtelemetry/gradle.properties
Update changelog for a new release of libtelemetry v8.1.0.
> [changelog] Update changelog for a new release of libtelemetry
