mapbox/mapbox-events-android

- .circleci/config.yml
- Adds `libtelemetry` CI instrumentation tests support
- Fixes #10 
- Adds Lint check step
👀 @electrostat
> Add libtelemetry CI instrumentation tests support

- liblocation/src/main/java/com/mapbox/services/android/core/location/AndroidLocationEngine.java
- liblocation/src/main/java/com/mapbox/services/android/core/location/LocationEngine.java
- liblocation/src/main/java/com/mapbox/services/android/core/location/LocationEnginePriority.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryService.java
Location Engine is currently hardcoded to `LocationEnginePriority.HIGH_ACCURACY`. Migrate to allowing developer to edit location engine priority to match their needs.
> Make Location Engine priority editable

- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryClient.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryClientSettings.java
Enables extra logging of telemetry request when activated. This is defaulted to off, but can be activated through a public api.
> Debug Logging API

- .circleci/config.yml
- Updates CI image to `mbgl/7d2403f42e:android-ndk-r16b` as in https://github.com/mapbox/mapbox-gl-native/pull/10695
> Update CI image

- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryClient.java
- libtelemetry/src/test/java/com/mapbox/services/android/telemetry/MockWebServerTest.java
- libtelemetry/src/test/java/com/mapbox/services/android/telemetry/TelemetryClientAppUserTurnstileEventTest.java
- libtelemetry/src/test/java/com/mapbox/services/android/telemetry/TelemetryClientLocationEventTest.java
- libtelemetry/src/test/java/com/mapbox/services/android/telemetry/TelemetryClientMapEventsTest.java
- libtelemetry/src/test/java/com/mapbox/services/android/telemetry/TelemetryClientNavigationEventsTest.java
- libtelemetry/src/test/java/com/mapbox/services/android/telemetry/TelemetryClientTest.java
- Removes `sendEvent` from `TelemetryClient` and fix all related tests.
> Remove send a single event method and use sendEvents instead

- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/Event.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/MapEventFactory.java
- libtelemetry/src/test/java/com/mapbox/services/android/telemetry/MapEventFactoryTest.java
- libtelemetry/src/test/java/com/mapbox/services/android/telemetry/TelemetryClientMapEventsTest.java
- Adds `createMapLoadEvent` method in order to remove the necessity of creating an empty `MapState` when creating `MAP_LOAD` events
> Remove map state object creation when building a map load event

- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/MapBuildEvent.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/MapEventFactory.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/test/java/com/mapbox/services/android/telemetry/MapEventFactoryTest.java
- libtelemetry/src/test/java/com/mapbox/services/android/telemetry/MapboxTelemetryTest.java
- libtelemetry/src/test/java/com/mapbox/services/android/telemetry/TelemetryClientMapEventsTest.java
- Holds an application `Context` within `MapboxTelemetry` and use it across the different classes that need one (removing the necessity of asking for it again and again)
> Request application context once and only once

- libtelemetry/src/main/java/com/mapbox/android/telemetry/NavigationMetadata.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/NavigationEventFactoryTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/SerializerTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientNavigationEventsTest.java
- Fixes hardcoded event version in navigation general metadata adding `eventVersion` parameter to `NavigationMetadata` constructor
👀 @electrostat @zugaldia @danesfeder @ericrwolfe
> Fix hardcoded event version in navigation general metadata

- libtelemetry/src/main/java/com/mapbox/android/telemetry/AppUserTurnstile.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/AppUserTurnstileTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MockWebServerTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientAppUserTurnstileEventTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientNavigationEventsTest.java
Make userId required in constructor for AppUserTurnstile event. This allows clients to add in their own unique Mapbox vendor id.
> Make userId required for AppUserTurnstile

- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapEventFactory.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapLoadEvent.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MapEventFactoryTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientMapEventsTest.java
Spec changed to require UserId for MapLoadEvent
> Require UserId for MapLoadEvent

- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
- Adds non-null `Context` required check when creating a `MapboxTelemetry` instance
> Add non-null context required check

- libtelemetry/src/main/java/com/mapbox/android/telemetry/ChinaServerInformation.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/ComServerInformation.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/EnvironmentChain.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/EnvironmentResolver.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/Logger.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/ServerInformation.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/StagingServerInformation.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClient.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClientBuild.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClientFactory.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClientSettings.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientFactoryTest.java
- Fixes hardcoded (`STAGING`) `TelemetryClientSettings` configuring them internally when created
> Fix hardcoded telemetry client settings

- liblocation/src/main/java/com/mapbox/android/core/location/AndroidLocationEngine.java
- liblocation/src/main/java/com/mapbox/android/core/location/GoogleLocationEngine.java
- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
- liblocation/src/main/java/com/mapbox/android/core/location/LocationEnginePriority.java
- liblocation/src/main/java/com/mapbox/android/core/location/LostLocationEngine.java
- liblocation/src/main/java/com/mapbox/services/android/core/location/UpdateAndroidProvider.java
- liblocation/src/main/java/com/mapbox/services/android/core/location/UpdateGoogleRequestPriority.java
- liblocation/src/main/java/com/mapbox/services/android/core/location/UpdateLostRequestPriority.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
Restrict value that can be set for location engine priority, utilizing enum paradigm.
> Ensure that Location Engine priority is set in the correct range 

- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/SessionInterval.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/SessionIntervalTest.java
Follow up from https://github.com/mapbox/mapbox-events-android/pull/32
- Checks that the rotation interval time passed in is an integer in the range of 1 to 24 hours
> Check sessionId rotation interval time in range

- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryListener.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MapEventFactoryTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientMapEventsTest.java
Make callback optional when creating MapboxTelemetry, so developer does not need to subscribe to the TelemetryClient Callback.
> MapboxTelemetry - Optional Callback

- libtelemetry/src/main/java/com/mapbox/android/telemetry/AppUserTurnstile.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/AppUserTurnstileTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MockWebServerTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientAppUserTurnstileEventTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientNavigationEventsTest.java
Remove enabledTelemetry param from AppUserTurnstile initialization and use previously created 'retrieveEnabledTelemetry' method in TelemetryUtils.
> Remove enabledTelemetry param

- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineProvider.java
Remove lost from LocationEngineProvider to help crash associated with including Lost dependency
> Remove LOST from LocationEngineProvider

- LICENSE
Cameron's license year update in the plugins repo (https://github.com/mapbox/mapbox-plugins-android/pull/249/files) spurred me to check our other repos. Kathleen confirmed that the years should be updated. This pr updates this repo's license. I've set an annual reminder on January 1st to check and update repos as needed.
> Updated license year to 2018

- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapClickEvent.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapDragendEvent.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapState.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MapEventFactoryTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientMapEventsTest.java
- Changes `MapState` to `double` instead of `float`
👀 @electrostat @zugaldia @tobrun
> Change MapState to double instead of float

- libtelemetry/src/main/java/com/mapbox/android/telemetry/Environment.java
- Makes `Environment` `enum` package private
> Make Environment enum package private

- libtelemetry/build.gradle
- Removes `multiDexEnabled true` line in order to avoid `com.android.support:multidex:1.0.1` dependency leak
> Remove multiDexEnabled true line

- gradle/dependencies.gradle
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClientSettings.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MockWebServerTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientTest.java
- Fixes #69 
- Bumps OkHttp version to `3.10.0`
- Adds `hostnameVerifier` to `TelemetryClientSettings` builder needed to workaround stuck MockWebServer tests after bumping OkHttp version to `3.10.0`. For further details 👉 https://github.com/square/okhttp/issues/3898
cc @electrostat @zugaldia @tobrun @LukasPaczos
> Update OkHttp version to 3.10.0

- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- Fixes #66 
- Removes `System.out` call from `MapboxTelemetry`
> Remove System.out call from MapboxTelemetry

- libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/AlarmReceiverInstrumentationTest.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/AlarmReceiver.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/AlarmSchedulerFlusher.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/SchedulerFlusherFactory.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/AlarmSchedulerFlusherTest.java
- Fixes overwritten alarms issue when having multiple instances of `MapboxTelemetry`
> Fix overwritten alarms issue

- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
- Brings back the `MOCK` `LocationEngine.Type`
Fixes #82 
cc @zugaldia @electrostat
> Bring back the Mock location engine type

- gradle/dependencies.gradle
- libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/EventReceiverInstrumentationTest.java
- libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/LocationReceiverInstrumentationTest.java
- libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/TelemetryServiceTest.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/EventReceiver.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/EventSender.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationReceiver.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryEnabler.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryLocationEnabler.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryReceiver.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/AppUserTurnstileTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/LocationReceiverTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MapEventFactoryTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientMapEventsTest.java
- Fixes duplicate location data issue when having multiple instances of `MapboxTelemetry`
Now `MapboxTelemetryService` (singleton by definition) is responsible for pushing the location fixes received into a single `queue` which is injected once after creating the `Service`, ensuring that only one instance of `MapboxTelemetry` receives the location events.
> Fix duplicate location data issue

- liblocation/src/main/java/com/mapbox/android/core/location/AndroidLocationEngine.java
Currently, the `AndroidLocationEngine` ignores `fastestInterval` and `smallestDisplacement` variables in favor of static constants.  This PR adds the set variables to the request when we ask the location manager for updates. 
cc @LukasPaczos @tobrun
> Set fastestInterval and smallestDisplacement in AndroidLocationEngine

- .circleci/config.yml
Partial solution is to save and restore dependencies at build time.
> Fix Circle-Ci not Downloading Dependencies

- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
- Fixes crash when `STICKY` `Service` is recreated
This is a release blocker so for now the solution taken is making the `Service` `NOT_STICKY`.
Will open a new ticket to revisit this and fix that back.
Fixes #97 
> Fix crash when sticky service is recreated

- libtelemetry/src/main/java/com/mapbox/android/telemetry/NavigationMetadata.java
- Removes unnecessary audio type setter from NavigationMetadata (it's not an optional field anymore)
> Remove unnecessary audio type setter from navigation metadata

- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
- Exposes `TelemetryUtils#obtainUniversalUniqueIdentifier` method publicly
> Expose obtain universal unique identifier method publicly

- libtelemetry/src/main/java/com/mapbox/android/telemetry/AlarmSchedulerFlusher.java
- Adds `try catch` for the cases in which the OS has unexpectedly unregistered the alarm (shouldn't happen but seen crashes in Samsung devices 👉 http://crashes.to/s/f54a1694773)
> Add Alarm unregistering safe check

- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
Updated javadocs associated with `fastestInterval` and `interval` to be explicit on function of `fastestInterval` when using an `AndroidLocationEngine`
> FastestInterval Documentation Update

- README.md
Part of the telem 3.0.0 and core 0.2.0 releases: https://github.com/mapbox/mapbox-events-android/issues/112
> Bumped libcore to 0.2.0 in README

- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- Adds service running check for the cases in which the OS has unexpectedly unregistered the service (shouldn't happen but seen crashes in Samsung devices 👉 https://github.com/mapbox/mapbox-gl-native/issues/11673#issuecomment-381247571)
cc @electrostat @tobrun @zugaldia @masterjefferson
> Add service running check

- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- Removes unnecessary `TelemetryEnabler#updateTelemetryState` from `enable` and `disable` methods
In order to avoid problems when having multiple instances of `MapboxTelemetry` the state should be updated from one single point 👉 [`AttributionDialogManager`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java).
cc @zugaldia @electrostat @danesfeder
> Remove unnecessary update telemetry state from enable and disable methods

- libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationJobService.java
MapboxTelemetry.applicationContext is `null` when application containing telem sdk is force closed. 
Fixes https://github.com/mapbox/mapbox-events-android/issues/124
> JobScheduler Context Bug

- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
Check if service is running and if it is, then unbind and continue on process. Prevents crash and keeps system working.
> Bug Fix for attempting to unbind a service that is already unregistered

- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
Under certain circumstances, a LocationEvent will be created while `MapboxTelemetry.applicationContext` is null. Add in check and set correct context when creating event.
> Missing Application Context

- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
Under certain circumstances, `TelemetryLocationEnabler` is null. Add in check to initialize, before being used.
> TelemetryLocationEnabler Null Bug 

- gradle/dependencies.gradle
Telemetry and core libraries no longer require MAS, likely an artifact of an earlier iteration of the libraries. Removing unnecessary dependency.
Fixes https://github.com/mapbox/mapbox-events-android/issues/162
> Remove MAS

- liblocation/src/main/java/com/mapbox/android/core/location/GoogleLocationEngine.java
GoogleLocationEngine will crash when requestingLocation due to a lack of priority, unless it is manually set by the dev. Set and create a default priority level of `NO_POWER` to fix this issue.
Fixes https://github.com/mapbox/mapbox-events-android/issues/169
Fixes https://github.com/mapbox/mapbox-events-android/issues/132
> GoogleLocationEngine lack of priority crash

- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
Reduce API level of current state check for `startService`. Was able to test solution on devices running Lollipop and above.
Fixes https://github.com/mapbox/mapbox-events-android/issues/174 for devices running Lollipop+, need to obtain test devices for lower API levels.
> Reduce API level for Current State check to Lollipop

- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
Our SDK currently crashes when a user disables location permissions manually (through the Android settings) and returns to the parent application. LocationEngine is attempting to acquire location without permission. 
Change was to add in both pre and post api 23 permission check before activating the engine. 
Fixes https://github.com/mapbox/mapbox-events-android/issues/182#issuecomment-405951475
> Crash When Disabling Location Permissions Manually

- libcore/proguard-consumer.pro
Change proguard rules for GMS to prevent a non-functioning GoogleLocationEngine
Fixes https://github.com/mapbox/mapbox-events-android/issues/185
> Update Proguard Rules for GMS

- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
Add `checkApplicationContext()` to workflow of stopping `TelemetryService`. This will prevent a NPE when attempting to run processes on service shutdown under certain circumstances.
Fixes https://github.com/mapbox/mapbox-events-android/issues/181
> checkApplicationContext when stopping service

- libtelemetry/src/main/java/com/mapbox/android/telemetry/Event.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/VisionBuildEvent.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/VisionEvent.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/VisionEventFactory.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/VisionEventFactoryTest.java
Create a general vision event for the initial integration of the telemetry sdk into the Vision sdk. Will allow VisionSDK to send back custom telemetry data and iterate during testing.
> Create General VisionEvent

- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
Add `mapbox-maps-android` user agent to list of acceptable user agents to standardize reporting across iOS and Android.
Fixes https://github.com/mapbox/mapbox-events-android/issues/177
cc: @lilykaiser
> Add maps user agent

- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryEnabler.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryLocationEnabler.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
Add null checks within parent methods for `obtainSharedPreferences` 
Fixes https://github.com/mapbox/mapbox-gl-native/issues/12748
> Add null checks for obtainSharedPreferences

- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
With https://github.com/mapbox/mapbox-navigation-android/pull/1039, the navigation repository is removing the `MockLocationEngine` in favor of a `ReplayRouteLocationEngine`.  
This PR is just updating the `Type` `enum` to better reflect the new naming on our side.  If this doesn't make sense or there is a better way to address this, I'm happy to update this PR or close.  
cc @andrlee
> Update MOCK LocationEngine Type to REPLAY

- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
Per @Guardiola31337's comment > https://github.com/mapbox/mapbox-events-android/pull/215#issuecomment-420947181 it might make sense to re-add the `MOCK` type to avoid a SEMVER major breakage.  
Ultimately up to ya'll @electrostat @andrlee, thanks for the 👀
> Re-add MOCK LocationEngine Type

- app/build.gradle
- libtelemetry/proguard-consumer.pro
Revisiting the proguard configuration [downstream](https://github.com/mapbox/mapbox-gl-native/pull/12929) showed that many warnings and notes were coming from the telemetry library. This PR revisits the telemetry proguard configuration by:
- relying on the [default](https://github.com/square/okhttp/blob/master/okhttp/src/main/resources/META-INF/proguard/okhttp3.pro) okhttp configuration.
- `dontnote sun.misc.Unsafe`, which is safe to don't note when using gson.
- don't note `duplicate class definitions` see  https://issuetracker.google.com/issues/37070898 for context.
> Telemetry proguard configuration

- libcore/proguard-consumer.pro
Update proguard rules to be more specific and lower method counts. We utilize `common` and `location` within the `Core` library and will keep only those.
fixes https://github.com/mapbox/mapbox-events-android/issues/199
> More specific Proguard rules

- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
Under certain circumstances, `telemetryService` is null and causes a crash when calling `obtainBoundInstances()` within `stopTelemetryService`. Add in check to prevent crash.
Fixes https://github.com/mapbox/mapbox-events-android/issues/188
> StopTelemetryService obtainBoundInstances bug fix

- libtelemetry/src/main/java/com/mapbox/android/telemetry/Event.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapEventFactory.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapOfflineEvent.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MapEventFactoryTest.java
This PR adds a new `MapOfflineEvent` event to the Maps SDK list of events.
It's still a WIP - not all fields are finalized, and tests are missing.
cc: @electrostat @Guardiola31337 for early eyes.
> Offline maps event

- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
Prevent `FileAttachment` event from being added to queue, in addition to sending it up through attachment logic.
Add in unit test to confirm that `whitelisted` events are not added to queue.\
Fixes https://github.com/mapbox/mapbox-events-android/issues/225
> Fix FileAttachment Queue Bug

- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
Detect if `ACCESS_FINE_LOCATION` permission has been removed from the manifest and throw an exception.
Fixes https://github.com/mapbox/mapbox-events-android/issues/222
> ACCESS_FINE_LOCATION permission exception

- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
Check if `MapboxTelemetry.applicationContext` is `null` when checking location permissions.
Fixes https://github.com/mapbox/mapbox-events-android/issues/234
> PermissionChecker NPE

- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineResult.java
As per @yunikkk 's suggestion - adding `@Nullable` annotation to `LocationEngineResult#getLastLocation()` method
> Add @Nullable annotation to getLastLocation method

- libtelemetry/src/main/java/com/mapbox/android/telemetry/BluetoothAudioType.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/HeadphonesAudioType.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationEvent.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationMapper.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationReceiver.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapClickEvent.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapDragendEvent.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapEventFactory.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapLoadEvent.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/NavigationMetadata.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/NavigationState.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/NavigationUtils.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/SchedulerFlusherFactory.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/SpeakerAudioType.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryEnabler.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/LocationEventTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/LocationMapperTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/SerializerTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientLocationEventTest.java
Fix crashes and introduce temporary refactor for `TelemetryUtils` class until libtelemetry is fully rewritten. 
Although this change is backwards compatible, it impacts @mapbox/navigation-android. Specifically, `NavigationState` class, which public constructor became deprecated.
```
@Deprecated
public NavigationState(NavigationMetadata navigationMetadata) {
this.navigationMetadata = navigationMetadata;
}
```
the new recommended way of instantiating this class is via this static factory:
```
public static NavigationState create(NavigationMetadata navigationMetadata, Context context) {
return new NavigationState(navigationMetadata.setDeviceInfo(context));
}
``` 
The motivation behind this change is extracting `Context` as much as possible from utility class. What it means for navigation …
> Fix crash due to null context reference in LocationBroadcastReceiver

- app/build.gradle
- liblocation/build.gradle
- libtelemetry/build.gradle
Fixing proguard warnings by removing jacoco from release builds. Addresses https://github.com/mapbox/mapbox-events-android/issues/302
> Remove jacoco from release builds

- libtelemetry/src/main/java/com/mapbox/android/telemetry/Event.java
Remove abstract `obtainType` to enable event creation outside of telemetry sdk. This change is done with a focus on preserving current telem sdk api signatures.
An open question: since we don't have any events outside of telem sdk yet, should we remove `Parcelable` dependency before we expose it to public? Can we do it without doing a major release?
/cc @mapbox/android
> Enable event creation outside of telem sdk

- .circleci/config.yml
- build.gradle
- gradle/dependencies.gradle
- libcore/build.gradle
- liblocation/build.gradle
- libtelemetry/build.gradle
Refs https://github.com/mapbox/mapbox-gl-native/issues/13598.
> Prepare the repository as Maps SDK vendor

- libtelemetry/build.gradle
Exclude unused dependencies associated with `LifecycleExtensions`.
Addresses: https://github.com/mapbox/mapbox-events-android/issues/273
> Remove Unused Lifecycle Dependencies

- libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/CertificateBlacklistInstrumentationTests.java
- libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/ConfigurationClientInstrumentationTest.java
- libtelemetry/src/main/AndroidManifest.xml
- libtelemetry/src/main/java/com/mapbox/android/telemetry/CertificateBlacklist.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/ConfigurationClient.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/ConfigurationClientTest.java
Add additional testing (unit and instrumentation) for Blacklist and ConfigurationClient. Goal is to increase test coverage, handle corner cases better, and prepare for wider array of testing platforms (api levels + devices).
Fixes: https://github.com/mapbox/mapbox-events-android/issues/330
> Additional Testing Around Blacklist and ConfigurationClient

- .circleci/config.yml
- Makefile
- gradle/mvn-push-android.gradle
- libcore/javadoc.gradle
- libtelemetry/gradle.properties
- libtelemetry/javadoc.gradle
Addresses: https://github.com/mapbox/mobile-telemetry/issues/272
Change pipeline system to release `Lite` and `Full` SDK on maven. Currently neither is working properly due to `Lite` refactor.
> Release Telemetry SDK Lite on Maven

- gradle/mvn-push-android.gradle
Apps fail to resolve `libcore` due to incorrect `artifactId`. Fix is ugly but there's no better way to override project name property programmatically since it's readonly. Tested with `mavenLocal` and `app` module.
> Fix pom artifactId for libcore dependency

- app/src/androidTest/java/com/mapbox/android/events/testapp/MainActivityInstrumentationTests.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/AlarmSchedulerFlusher.java
- libtelemetry/src/testFull/java/com/mapbox/android/telemetry/AlarmSchedulerFlusherTest.java
Run into a crash while testing
```
java.lang.NullPointerException: cancel() called with a null PendingIntent
at android.app.AlarmManager.cancel(AlarmManager.java:916)
at com.mapbox.android.telemetry.AlarmSchedulerFlusher.unregister(AlarmSchedulerFlusher.java:56)
at com.mapbox.android.telemetry.MapboxTelemetry.stopAlarm(MapboxTelemetry.java:433)
at com.mapbox.android.telemetry.MapboxTelemetry.stopTelemetry(MapboxTelemetry.java:538)
at com.mapbox.android.telemetry.MapboxTelemetry.disable(MapboxTelemetry.java:139)
at com.mapbox.android.events.testapp.MainActivity.onDestroy(MainActivity.java:37)
```
Root cause is that PendingIntent is inited in
```
public void register() {
Intent alarmIntent = receiver.supplyIntent();
pendingIntent = PendingIntent.getBroadcast(context, 0, alarmIntent, 0); …
```
> Add null check for pending Intent

- gradle/dependencies.gradle
- liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineRequest.java
Reset default `displacement` value to 0 due to potential delay with first location update on Pie that  takes 30 seconds - 1 min. We've not seen this behavior on pre-Pie api versions, so the assumption is that changes in framework were made that no longer work well with default displacement value we had tested with previously.
/cc @danesfeder @Guardiola31337
> Fix GoogleLocationEngine intermittent delayed updates

- gradle/dependencies.gradle
- libtelemetry/build.gradle
Fixes: https://github.com/mapbox/mapbox-events-android/issues/359
Replace `localbroadcastmanager` and `support-compat` with `support-core-utils`. Also, downgrade support libraries to `27.1.1` to match the support library within the Maps SDK
> Mismatched Dependency Issue 

- libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationCollectionClient.java
Add version number to the `userAgent` field of location collector. Default `userAgent: mapbox-android-location/x.x.x`
> Add version to location collector userAgent

- libtelemetry/src/full/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationCollectionClient.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/EventsQueue.java
**Problem:**
Ran on crash while doing pre-release testing with maps sdk test app. `MapSnapshotter` test chocked up the executor's queue and resulted in the its crash:
```
Process: com.mapbox.mapboxsdk.testapp, PID: 11852
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapbox.mapboxsdk.testapp/com.mapbox.mapboxsdk.testapp.activity.fragment.MultiMapActivity}: android.view.InflateException: Binary XML file line #59: Binary XML file line #59: Error inflating class fragment
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2679)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2740)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1487)
at …
```
> Handle executor errors

- libtelemetry/src/main/java/com/mapbox/android/telemetry/GzipRequestInterceptor.java
Resolves #357 
There is a strict mode issue while running test app
```
StrictMode: StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2023)
```
Root cause
Solution:
Add call TrafficStats.setThreadStatsTag(THREAD_ID); in `com.mapbox.android.telemetry.GzipRequestInterceptor.intercept`
> Resolve strict mode UntaggedSocketViolation issue

- libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/location/LocationCollectionClientInstrumentedTest.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationCollectionClient.java
Some test cases in `LocationCollectionClientInstrumentedTest` is unstable, use `CountDownLatch` to instead of `sleep`.
In `unInstall` method of `LocationCollectionClientInstrumentedTest`, we don't unregister listener, so it will not release current object. Call `unregisterOnSharedPreferenceChangeListener` to fix it.
> Fix unstable test cases in LocationCollectionClientInstrumentedTest

- libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/location/LocationCollectionClientInstrumentedTest.java
Since we will install LocationCollectionClient in the content provider as long as the target app is started, it will install and create  a LocationCollectionClient instance with default parameter. In this test,  the `install ` function in `setup` method will not works for the first test case.
In order to eliminate the influence on test cases, we should call `uninstall` in `setup` instead of `tearDown`.
> Call uninstall in setup method of LocationCollectionClientInstrumentedTest

- libcore/src/androidTest/java/com/mapbox/android/core/crashreporter/MapboxUncaughtExceptionHanlderInstrumentationTest.java
- libcore/src/main/java/com/mapbox/android/core/crashreporter/MapboxUncaughtExceptionHanlder.java
This fixes handling of cleanup logic when we reach max allowed reports in the root directory. 
Fix misused `File#length` api, with listing all files in the root directory and counting size of its array.
Tested with instrumentation tests and manually with maps sdk test app.
> Fix crash file counting bug

- libcore/src/androidTest/java/com/mapbox/android/core/crashreporter/CrashReportBuilderInstrumentedTest.java
- libcore/src/androidTest/java/com/mapbox/android/core/crashreporter/MapboxUncaughtExceptionHanlderInstrumentationTest.java
- libcore/src/main/java/com/mapbox/android/core/crashreporter/MapboxUncaughtExceptionHanlder.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/AlarmReceiver.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/crash/CrashReporterClient.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationCollectionClient.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/provider/MapboxTelemetryInitProvider.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/EventsQueue.java
This PR implements improved top level error handling per every thread that telemetry library manages internally. Solution is to catch all top level exceptions and log them as silent crashes (in future when silent crashes are added to the exception handler). 
End user should not be impacted by top level exceptions that telemetry has full control of. Tested this change with maps sdk test app.
> Improved error handling

- .circleci/config.yml
Trigger release job when git-tag is submitted and manage version update automatically (stolen from `gl-native` - thanks to @tobrun).
> Trigger release job on CI with git tags

- CHANGELOG.md
- libtelemetry/gradle.properties
Update release notes and bump snapshot version: https://github.com/mapbox/mapbox-events-android/issues/386
> Telemetry 4.4.0 release

- .circleci/config.yml
- libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/crash/CrashReporterClientInstrumentationTest.java
Telemetry library was accidentally published with `libcore` snapshot dependency. It happened since `VERSION_NAME` of the `libcore` was not updated at the time of release, which could either be done manually at every release cycle or provided via git tag. The format of the git tag for telemetry releases:
`telem-MAJOR.MINOR.PATCH-core-MAJOR.MINOR.PATCH`
> Publish telemetry release with specific version of released libcore

- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
Fixing crash due to `context#registerReceiver` on the device with buggy firmware. The crash report was received from `msm8996` device.
> Fix crash due to buggy firmware

- app/build.gradle
- gradle/dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
- libtelemetry/build.gradle
A month ago we upgraded to `okhttp 3.14.0` based on the request from the maps team: https://github.com/mapbox/mapbox-events-android/issues/375, unfortunately this version of `okhhtp` requires min `Android 5.0` and will result in crash on lower versions of the OS.
> Revert okhttp to version 3.12.0

- libtelemetry/src/full/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetryConstants.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClient.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClientSettings.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientTest.java
- libtelemetry/src/testFull/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
Problem
Vision team need to change telemetry url at runtime depending on a current country.
Solution
Was decided to add a public API to `mapbox-events-android` lib change telemetry url dynamically.
Test
Unit tests were added to check if a new url is valid and a telemetry client receives setting with a new base url.
closes [1336](https://app.zenhub.com/workspaces/vision-sdk-5ca52e6c027e3e7234ac7512/issues/mapbox/mapbox-vision/1336)
> Add public api to change baseUrl for telemetry

- README.md
This pr updates the core SNAPSHOT README section to not hardcode an outdated SNAPSHOT version.
> README update for core SNAPSHOT section

- build.gradle
- gradle/dependencies.gradle
- libcore/src/androidTest/java/com/mapbox/android/core/CoreSDKVersionTest.java
- libcore/src/main/assets/sdk_versions/com.mapbox.android.core
- libcore/src/main/java/com/mapbox/android/core/FileUtils.java
- libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/TelemetrySDKVersionTest.java
- libtelemetry/src/main/assets/sdk_versions/com.mapbox.android.telemetry
This plugin https://github.com/mapbox/android-sdk-versions-plugin validates and persists the SDK version into a file in assets folder. This information further feeds into Reformed User Agent.
https://github.com/mapbox/mobile-telemetry/issues/452
https://github.com/mapbox/mobile-telemetry/issues/423
> Apply android-sdk-versions-plugin to Telemetry and Core modules

- CHANGELOG.md
- libtelemetry/src/full/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/testFull/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
PR fixes issue [424](https://github.com/mapbox/mapbox-events-android/issues/424)
> Null pointer fix 

- libcore/gradle.properties
- libtelemetry/gradle.properties
Set Core/Telem versions in gradle.properties to 1.4.1-SNAPSHOT/4.7.1-SNAPSHOT
> Bump Core and Telemetry versions

- gradle/dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
Update gradle versions to the latest stable releases.
https://developer.android.com/studio/releases/gradle-plugin
Gradle Version : 5.6.4
Android Gradle Plugin Version : 3.5.3
> Update Gradle Versions

- package.json
Node 8 gets to EOL in Dec 2019. It is recommended to update to the latest node version as mentioned here:
https://github.com/mapbox/telemetry/issues/572
> Update Node version to >=10

- libcore/src/main/assets/sdk_versions/com.mapbox.android.core
- libtelemetry/src/full/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/main/assets/sdk_versions/com.mapbox.android.telemetry
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
Untagged socket detection is one of the anomalies detected by Strict Mode in android from Android O. Since the Telemetry Test app enables the Strict mode with penalty death in debug mode, the app crashes/freezes on installation.
Strict mode expects a tag set to every thread and the threads created by Okhttp sockets does not not seem to do so for different reason. This is still an open issue
https://github.com/square/okhttp/issues/3537
This pull request adds custom socket factory and sets TrafficStats.setThreadStatsTag(1000) for configuration client(okhttpClient). The main Telemetry Client has the similar workaround that already in place.
https://github.com/mapbox/mapbox-events-android/blob/22367f5acbbd27183b7c539a5dd8ba96cb59d159/libtelemetry/src/main/java/com/mapbox/android/telemetry/Gzip …
> Workaround for Strict mode Untagged Socket issue

- .circleci/config.yml
- cloud_test.sh
- libcore/src/androidTest/java/com/mapbox/android/core/crashreporter/CrashReportBuilderInstrumentedTest.java
- libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/AlarmMangerInstrumentationTest.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/AlarmSchedulerFlusher.java
Resolves #410 
Instrumentation tests will run on more devices for release.
> Add test device for CI in release process

- CHANGELOG.md
- Upgrade to AndroidX [#446] (https://github.com/mapbox/mapbox-events-android/pull/446)
- Revert "Add test device for CI in release process [#449] (https://github.com/mapbox/mapbox-events-android/pull/449)
- Add test device for CI in release process  [#417] (https://github.com/mapbox/mapbox-events-android/pull/417)
- Workaround for Strict mode socket issue [#443] (https://github.com/mapbox/mapbox-events-android/pull/443)
- Update Node version to >=10 [#445] (https://github.com/mapbox/mapbox-events-android/pull/445))
- Update Gradle Versions [#444] (https://github.com/mapbox/mapbox-events-android/pull/444)
> Update ChangeLog.md for release 4.7.1/1.4.1

- CHANGELOG.md
- libcore/gradle.properties
- libcore/src/main/assets/sdk_versions/com.mapbox.android.core
- libtelemetry/gradle.properties
- libtelemetry/src/main/assets/sdk_versions/com.mapbox.android.telemetry
Bump version to 5.0.1-SNAPSHOT for Telemetry
Bump version to 2.0.1-SNAPSHOT for Core.
Update changelog.md .
> Pre Release 5.0.0/2.0.0: Bump version for future releases and update changelog.md 

- libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/TestCellularNetworkType.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/SchemaTest.java
TelephonyManager.getNetworkType() is deprecated in API level 30, so
using getDataNetworkType() to get the current data network type on
newer android OS.
Co-authored-by: Tobrun Van Nuland <tobrun.van.nuland@gmail.com>
> Fix a crash on newer android OS due to a depreacted API usage

- libtelemetry/src/test/java/com/mapbox/android/telemetry/SchemaTest.java
We don't test at the moment any `userAgent` values, let's do the same for `mapboxAgent` field.
> [telemetry, test] Exclude mapboxAgent field for testing

- README.md
This pr updates the README to use implementation instead of compile
> Updated README to use implementation instead of compile

- libtelemetry/src/main/java/com/mapbox/android/telemetry/ComCertificatePins.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/CertificatePinnerFactoryTest.java
Okhttp allows to use asterisks for domain matching like:
`**.square.com` for matching all subdomains. We can do the same to avoid
having the list of different domains for pinning certificates.
> [telemetry] Use asterisks for domain matching in CertificatePinner

- libtelemetry/src/full/AndroidManifest.xml
- libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationMapper.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationUpdatesBroadcastReceiver.java
- libtelemetry/src/testFull/java/com/mapbox/android/telemetry/location/LocationUpdatesBroadcastReceiverTest.java
Get and send the background/foreground state of an application in location events.
Fixes https://github.com/mapbox/core-sdk-team/issues/525
> [telemetry] Add foreground/background information to location events.

- CHANGELOG.md
- libcore/gradle.properties
- libtelemetry/gradle.properties
`telemetry-6.2.2-core-3.1.1`
- [telemetry] track foreground and background application states and send with events
- [core] LocationEngineRequest supports Equality and Hashing
> telemetry-6.2.2-core-3.1.1

- libcore/src/androidTest/java/com/mapbox/android/core/crashreporter/CrashReportBuilderInstrumentedTest.java
- libcore/src/androidTest/java/com/mapbox/android/core/crashreporter/CrashReportFactoryInstrumentedTest.java
- libcore/src/androidTest/java/com/mapbox/android/core/crashreporter/MapboxUncaughtExceptionHanlderInstrumentationTest.java
- libcore/src/main/java/com/mapbox/android/core/crashreporter/CrashReportBuilder.java
- libcore/src/main/java/com/mapbox/android/core/crashreporter/CrashReportFactory.java
- libcore/src/main/java/com/mapbox/android/core/crashreporter/MapboxUncaughtExceptionHanlder.java
- libcore/src/test/java/com/mapbox/android/core/crashreporter/CrashReportFactoryTest.java
- libcore/src/test/java/com/mapbox/android/core/crashreporter/MapboxUncaughtExceptionHanlderTest.java
- libcore/src/test/java/com/mapbox/android/core/utils/ErrorTestUtils.java
- libcore/src/test/java/com/mapbox/android/core/utils/NoStackTraceException.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/MapboxCrashReporter.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/errors/ErrorReporterClient.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/errors/ErrorUtils.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/SchemaTest.java
- libtelemetry/src/testFull/java/com/mapbox/android/telemetry/MapboxCrashReporterTest.java
This PR:
1) Adds support for reporting non-fatal exceptions via Telemetry SDK (in a similar way to iOS Telemetry SDK);
2) Improve `stackTrace` information: `stackTrace` now keeps more information about original stack trace (more classes might be allowed for keeping in stack trace, exception message also added to stack trace);
3) Fixes failed `SchemaTest`.
> Non-fatal exceptions reporting

- libcore/src/androidTest/java/com/mapbox/android/core/crashreporter/CrashReportFactoryInstrumentedTest.java
- libcore/src/androidTest/java/com/mapbox/android/core/crashreporter/CrashReportInstrumentedTest.java
- libcore/src/main/java/com/mapbox/android/core/crashreporter/CrashReport.java
- libcore/src/main/java/com/mapbox/android/core/crashreporter/CrashReportBuilder.java
- libcore/src/main/java/com/mapbox/android/core/crashreporter/CrashReportFactory.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/CrashEvent.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/KeyValue.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/MapboxCrashReporter.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/MapboxTelemetry.java
- libtelemetry/src/testFull/java/com/mapbox/android/telemetry/MapboxCrashReporterTest.java
This PR contains small improvements for non-fatal errors reporting:
1. Custom data support was added for non-fatal errors and crashes reporting;
2. Non-fatal errors are not sent immediately (for optimisation purpose).
> Improve non-fatal errors reporting

- libtelemetry/src/main/java/com/mapbox/android/telemetry/StagingCertificatePins.java
We just updated the certificate for `api-events-staging` and generated a new hash which I'm adding here to test pinning.
> Add a new hash for api-events-staging

- .circleci/config.yml
- liblocation/src/main/java/com/mapbox/android/core/location/MapboxFusedLocationEngineImpl.java
- liblocation/src/test/java/com/mapbox/android/core/location/MapboxFusedLocationEngineImplAdditionalTest2.java
This skips a location update that was determined as worse than the last one instead of delivering the old location update again, which is an unexpected behavior and causes problems downstream when integrating.
> [location] Skip a location update that was determined as worse than the last one.

- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
If the app doesn't have the correct permissions and we handle this gracefully - this should be a warning
> [telemetry] Downgrade getDataNetworkType() error to warning

- libtelemetry/src/main/java/com/mapbox/android/telemetry/StagingCertificatePins.java
Adding 5 new staging pins for 2048 bit keys. 
Part of [certificate rotation](https://github.com/mapbox/api-events/issues/701)
> Add 5 new pins for the staging endpoint 

- CHANGELOG.md
- libtelemetry/src/full/java/com/mapbox/android/telemetry/provider/MapboxTelemetryInitProvider.java
Resolves #530.
Workaround for the crash that can happen in multiple processes of WorkManager. The service functionality is tracking the lifecycle of the app's activity, so in case of background tasks, we can safely ignore this error.
> [telemetry] Workaround for `MapboxTelemetryService` crash.

- CHANGELOG.md
- gradle/dependencies.gradle
- libtelemetry/build.gradle
- libtelemetry/src/full/AndroidManifest.xml
- libtelemetry/src/full/java/com/mapbox/android/telemetry/AlarmSchedulerFlusher.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationEngineControllerImpl.java
- libtelemetry/src/testFull/java/com/mapbox/android/telemetry/location/LocationEngineControllerImplTest.java
> [telemetry]  Android 12 compartibility fixes.

- libtelemetry/src/full/java/com/mapbox/android/telemetry/AppStateUtils.java
- libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationUpdatesBroadcastReceiver.java
To avoid delays (~3-5ms) on the main thread.
Fixes  #537.
> [telemetry] Save and read application state on a background thread.

- CHANGELOG.md
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryEnabler.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/provider/MapboxTelemetryInitProvider.java
Do not run initialization via content provider if telemetry is permanently disabled through an app's manifest metadata.
> [telemetry] Disable `MapboxTelemetryInitProvider` if the telemetry is disabled via app's manifest.

- cloud_test.sh
Devices `hammerhead-21`, `sailfish-26` and `sailfish-28` are not available
anymore, replacing them with similar ones.
> [ci] Update Firebase test matrix.

- gradle/publish.gradle
- libcore/build.gradle
- libtelemetry/build.gradle
For `:libcore` and `:libtelemetry` artifacts downloaded from Mapbox Maven repository we cannot retrieve information about license, developers and etc. from POM file. This PR addresses this problem.
> [build] Attach more info to Maven publications uploaded with sdkRegistry

- libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/TestCellularNetworkType.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
`TelemetryUtils.obtainCellularNetworkType` is annotated with @NonNull
annotation meaning that this function should never return a null.
However before this change there was a way to return a null when
returned underlying network type is not covered in the `NETWORKS` map.
> [telemetry] Fix crash when using `obtainCellularNetworkType`

- libtelemetry/src/main/AndroidManifest.xml
- libtelemetry/src/main/java/com/mapbox/android/telemetry/AppStateUtils.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
> Fix `TelemetryUtils.obtainApplicationState()` method.

- cloud_test.sh
- libtelemetry/src/main/java/com/mapbox/android/telemetry/AttachmentMetadata.java
This will prevent Proguard / obfuscation issues with `AttachmentMetadata`
class.
> [libtelemetry] Add `@Keep` annotation to the AttachmentMetadata

- app/src/main/java/com/mapbox/android/events/testapp/MainActivity.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationEvent.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/location/LocationMapper.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/location/LocationUpdatesBroadcastReceiver.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/LocationEventTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/LocationMapperTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/SchemaTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientLocationEventTest.java
With this change, we are adding extra information about granted location permission to the location events:
* `AllowAlways` means that the end-user is allowed to collect location information while an application is in the background.
* `AllowWhenInUse` means that the end-user is allowed to collect location information while an application is in the foreground or only one-time access was granted.
> [location] Add new field `permissionStatus` to location events

- app/src/main/java/com/mapbox/android/events/testapp/MainActivity.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationEvent.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
- libtelemetry/src/main/java/com/mapbox/android/telemetry/location/LocationMapper.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/LocationEventTest.java
- libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientLocationEventTest.java
Take the timestamp of the location fix not from a system clock, but from the fix itself (i.e. value populated by system geolocation service).
> [libtelemetry] Fix LocationEvent timestamp.

- libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationEvent.java
In #566 we added `permissionStatus` parameter to the `LocationEvent` constructor. That change actually introduced a breaking change in the public API surface.
With this change, we are bringing an old constructor back and we use the `unknown` default value for the `permissionStatus`.
> [libtelemetry] Add `LocationEvent` constructor that doesn't accept `permissionStatus`

- .circleci/config.yml
- Makefile
- gradle/mvn-push-android.gradle
We do not practice maven repository publication for our projects anymore. We switched to our own sdk registry publication.
https://oss.sonatype.org/content/repositories/releases/ has very old mapbox versions (1 year and older for most projects).
we also never run `publish-core` and `publish-telem` by ci.
> Remove public maven repo publication.

- .circleci/config.yml
- libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/AlarmMangerInstrumentationTest.java
Mapbox does not practice publication of builds to public maven repo anymore
> Remove maven publication follow-up
